#!/bin/sh

enable_tty() {
	while true; do
		getty "$1" "$2" "$3"
	done
}

# mounting file systems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

mount -a

# creating fd symlinks in /dev
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

# setting hostname
hostname -F /etc/hostname

# enabling t9 input overlay and ttys themselves
t9tty /dev/input/event0 1 &
enable_tty 9600 ttyS0 linux &
enable_tty 9600 ttyS1 linux &
enable_tty 38400 tty1 linux &
enable_tty 38400 tty2 linux &
enable_tty 38400 tty3 linux &

# mission completed
sleep inf
